name: Hourly Profile Update Engine

on:
#   schedule:
#     - cron: '0 * * * *'       # Triggers automatically every hour
  workflow_dispatch:
    inputs:
      script:
        description: 'script to be executed'
        required: true
        default: 'script.py'
        type: choice
        options:
          - script.py
          - naukri_script.py
          - naukri_script2.py

jobs:
  execute-bot:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./naukri

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Initialize Python Runtime
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps chromium

      - name: Run Profile Refresher Script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python ${{ github.event.inputs.script }}
        continue-on-error: true

      - name: Export Debug Artifacts on Failure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-debug-artifacts
          path: ./naukri/
          retention-days: 5